name: rocksdb-server
version: '0.1.2'
summary: A server implementation for RocksDB
description: |
  This project provides a simple server implementation for RocksDB, a persistent key-value store for fast storage environments. 
  The server is designed to handle database operations over TCP connections, allowing clients to interact with the RocksDB instance remotely.

  Features:
  - CRUD Operations: Create, Read, Update, and Delete operations on RocksDB.
  - Batch Operations: Support for batch write operations.
  - Transactions: Begin, commit, and rollback transactions.
  - Column Families: Manage column families within the RocksDB instance.
  - Backup and Restore: Create and restore backups of the database.
  - Logging: Configurable logging levels.
  - Authentication: Optional token-based authentication for server access.
  - Custom Merge Operator: A JSON merge operator to handle JSON merge operations.

base: core20
confinement: strict

parts:
  rocksdb-server:
    source: .
    plugin: rust
    build-packages:
      - libclang-dev
    override-build: |
      export LIBCLANG_PATH=/usr/lib/llvm-10/lib
      snapcraftctl build -- --manifest-path=server/Cargo.toml

apps:
  rocksdb-server:
    command: bin/rocksdb_server
