[target.'cfg(not(target_os = "windows"))']
rustflags = ["-C", "link-arg=-Wl,-undefined,dynamic_lookup"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[target.i686-pc-windows-msvc]
linker = "rust-lld"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[env]
RUST_TEST_THREADS = "1"