name: Publish Homebrew Formula new

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-formula:
    name: Update Homebrew Formula
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Calculate SHA256 checksums and set version
        id: sha256
        run: |
          VERSION=$(grep '^version =' server/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          CLI_VERSION=$(grep '^version =' rocksdb-cli/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          APP_VERSION=$(jq -r '.package.version' rocksdb-viewer/src-tauri/tauri.conf.json)
          
          MACOS_X86_64_URL="https://github.com/s00d/RocksDBFusion/releases/download/server-v${VERSION}/rocksdb_server-Darwin-x86_64.tar.gz"
          MACOS_AARCH64_URL="https://github.com/s00d/RocksDBFusion/releases/download/server-v${VERSION}/rocksdb_server-Darwin-aarch64.tar.gz"
          LINUX_X86_64_URL="https://github.com/s00d/RocksDBFusion/releases/download/server-v${VERSION}/rocksdb_server-Linux-x86_64-musl.tar.gz"
          LINUX_AARCH64_URL="https://github.com/s00d/RocksDBFusion/releases/download/server-v${VERSION}/rocksdb_server-Linux-aarch64-musl.tar.gz"

          CLI_MACOS_X86_64_URL="https://github.com/s00d/RocksDBFusion/releases/download/rocksdb-cli-v${CLI_VERSION}/rocksdb_cli-Darwin-x86_64.tar.gz"
          CLI_MACOS_AARCH64_URL="https://github.com/s00d/RocksDBFusion/releases/download/rocksdb-cli-v${CLI_VERSION}/rocksdb_cli-Darwin-aarch64.tar.gz"
          CLI_LINUX_X86_64_URL="https://github.com/s00d/RocksDBFusion/releases/download/rocksdb-cli-v${CLI_VERSION}/rocksdb_cli-Linux-x86_64-musl.tar.gz"
          CLI_LINUX_AARCH64_URL="https://github.com/s00d/RocksDBFusion/releases/download/rocksdb-cli-v${CLI_VERSION}/rocksdb_cli-Linux-aarch64-musl.tar.gz"

          APP_MACOS_X86_64_URL="https://github.com/s00d/RocksDBFusion/releases/download/app-v${APP_VERSION}/rocksdb-viewer_${APP_VERSION}_x64.dmg"
          APP_MACOS_AARCH64_URL="https://github.com/s00d/RocksDBFusion/releases/download/app-v${APP_VERSION}/rocksdb-viewer_${APP_VERSION}_aarch64.dmg"

          MACOS_X86_64_SHA256=$(curl -L $MACOS_X86_64_URL | shasum -a 256 | awk '{print $1}')
          MACOS_AARCH64_SHA256=$(curl -L $MACOS_AARCH64_URL | shasum -a 256 | awk '{print $1}')
          LINUX_X86_64_SHA256=$(curl -L $LINUX_X86_64_URL | shasum -a 256 | awk '{print $1}')
          LINUX_AARCH64_SHA256=$(curl -L $LINUX_AARCH64_URL | shasum -a 256 | awk '{print $1}')

          CLI_MACOS_X86_64_SHA256=$(curl -L $CLI_MACOS_X86_64_URL | shasum -a 256 | awk '{print $1}')
          CLI_MACOS_AARCH64_SHA256=$(curl -L $CLI_MACOS_AARCH64_URL | shasum -a 256 | awk '{print $1}')
          CLI_LINUX_X86_64_SHA256=$(curl -L $CLI_LINUX_X86_64_URL | shasum -a 256 | awk '{print $1}')
          CLI_LINUX_AARCH64_SHA256=$(curl -L $CLI_LINUX_AARCH64_URL | shasum -a 256 | awk '{print $1}')

          APP_MACOS_X86_64_SHA256=$(curl -L $APP_MACOS_X86_64_URL | shasum -a 256 | awk '{print $1}')
          APP_MACOS_AARCH64_SHA256=$(curl -L $APP_MACOS_AARCH64_URL | shasum -a 256 | awk '{print $1}')

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CLI_VERSION=$CLI_VERSION" >> $GITHUB_ENV
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

          echo "MACOS_X86_64_SHA256=$MACOS_X86_64_SHA256" >> $GITHUB_ENV
          echo "MACOS_AARCH64_SHA256=$MACOS_AARCH64_SHA256" >> $GITHUB_ENV
          echo "LINUX_X86_64_SHA256=$LINUX_X86_64_SHA256" >> $GITHUB_ENV
          echo "LINUX_AARCH64_SHA256=$LINUX_AARCH64_SHA256" >> $GITHUB_ENV

          echo "CLI_MACOS_X86_64_SHA256=$CLI_MACOS_X86_64_SHA256" >> $GITHUB_ENV
          echo "CLI_MACOS_AARCH64_SHA256=$CLI_MACOS_AARCH64_SHA256" >> $GITHUB_ENV
          echo "CLI_LINUX_X86_64_SHA256=$CLI_LINUX_X86_64_SHA256" >> $GITHUB_ENV
          echo "CLI_LINUX_AARCH64_SHA256=$CLI_LINUX_AARCH64_SHA256" >> $GITHUB_ENV

          echo "APP_MACOS_X86_64_SHA256=$APP_MACOS_X86_64_SHA256" >> $GITHUB_ENV
          echo "APP_MACOS_AARCH64_SHA256=$APP_MACOS_AARCH64_SHA256" >> $GITHUB_ENV

      - name: Update Homebrew Formula
        run: |
          # Update rocksdb_server.rb formula
          FORMULA_FILE="homebrew/Formula/rocksdb_server.rb"
          VERSION=${{ env.VERSION }}
          MACOS_X86_64_SHA256=${{ env.MACOS_X86_64_SHA256 }}
          MACOS_AARCH64_SHA256=${{ env.MACOS_AARCH64_SHA256 }}
          LINUX_X86_64_SHA256=${{ env.LINUX_X86_64_SHA256 }}
          LINUX_AARCH64_SHA256=${{ env.LINUX_AARCH64_SHA256 }}

          echo "Updating formula at $FORMULA_FILE with version $VERSION"

          sed -i "s|{VERSION}|${VERSION}|g" "$FORMULA_FILE"
          sed -i "s|{MACOS_X86_64_SHA256}|${MACOS_X86_64_SHA256}|g" "$FORMULA_FILE"
          sed -i "s|{MACOS_AARCH64_SHA256}|${MACOS_AARCH64_SHA256}|g" "$FORMULA_FILE"
          sed -i "s|{LINUX_X86_64_SHA256}|${LINUX_X86_64_SHA256}|g" "$FORMULA_FILE"
          sed -i "s|{LINUX_AARCH64_SHA256}|${LINUX_AARCH64_SHA256}|g" "$FORMULA_FILE"

          # Update rocksdb_cli.rb formula
          CLI_FORMULA_FILE="homebrew/Formula/rocksdb_cli.rb"
          CLI_VERSION=${{ env.CLI_VERSION }}
          CLI_MACOS_X86_64_SHA256=${{ env.CLI_MACOS_X86_64_SHA256 }}
          CLI_MACOS_AARCH64_SHA256=${{ env.CLI_MACOS_AARCH64_SHA256 }}
          CLI_LINUX_X86_64_SHA256=${{ env.CLI_LINUX_X86_64_SHA256 }}
          CLI_LINUX_AARCH64_SHA256=${{ env.CLI_LINUX_AARCH64_SHA256 }}

          echo "Updating formula at $CLI_FORMULA_FILE with version $CLI_VERSION"

          sed -i "s|{VERSION}|${CLI_VERSION}|g" "$CLI_FORMULA_FILE"
          sed -i "s|{MACOS_X86_64_SHA256}|${CLI_MACOS_X86_64_SHA256}|g" "$CLI_FORMULA_FILE"
          sed -i "s|{MACOS_AARCH64_SHA256}|${CLI_MACOS_AARCH64_SHA256}|g" "$CLI_FORMULA_FILE"
          sed -i "s|{LINUX_X86_64_SHA256}|${CLI_LINUX_X86_64_SHA256}|g" "$CLI_FORMULA_FILE"
          sed -i "s|{LINUX_AARCH64_SHA256}|${CLI_LINUX_AARCH64_SHA256}|g" "$CLI_FORMULA_FILE"

          # Update rocksdb-viewer.rb cask
          CASK_FILE="homebrew/Casks/rocksdb-viewer.rb"
          APP_VERSION=${{ env.APP_VERSION }}
          APP_MACOS_X86_64_SHA256=${{ env.APP_MACOS_X86_64_SHA256 }}
          APP_MACOS_AARCH64_SHA256=${{ env.APP_MACOS_AARCH64_SHA256 }}

          echo "Updating cask at $CASK_FILE with version $APP_VERSION"

          sed -i "s|{VERSION}|${APP_VERSION}|g" "$CASK_FILE"
          sed -i "s|{MACOS_X86_64_SHA256}|${APP_MACOS_X86_64_SHA256}|g" "$CASK_FILE"
          sed -i "s|{MACOS_AARCH64_SHA256}|${APP_MACOS_AARCH64_SHA256}|g" "$CASK_FILE"

      - name: Deploy Docs
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: update-formula-branch
          build_dir: homebrew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v4
#        with:
#          token: ${{ secrets.GH_TOKEN }}
#          commit-message: Update Homebrew formula for version ${{ env.VERSION }}
#          committer: GitHub <noreply@github.com>
#          author: YOUR_NAME <YOUR_EMAIL>
#          title: Update Homebrew formula for version ${{ env.VERSION }}
#          body: |
#            This pull request updates the Homebrew formula to version ${{ env.VERSION }}.
#            - CLI version: ${{ env.CLI_VERSION }}
#            - App version: ${{ env.APP_VERSION }}
#          head-branch: update-formula-branch
#          base: master
#          labels: formula update
#          repo: Homebrew/homebrew-core
