name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            targets: x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu i586-unknown-linux-gnu powerpc-unknown-linux-gnu
          - os: macos-latest
            targets: x86_64-apple-darwin aarch64-apple-darwin
          - os: windows-latest
            targets: x86_64-pc-windows-msvc x86_64-pc-windows-gnu i686-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LLVM & Clang
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: 16
          directory: ${{ runner.temp }}/llvm-16
          cached: true

      - name: Configure Clang
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          echo "LIBCLANG_PATH=${{ runner.temp }}/llvm-16/lib" >> $GITHUB_ENV
          echo "LLVM_VERSION=${{ steps.clang.outputs.version }}" >> $GITHUB_ENV
          echo "LLVM_CONFIG_PATH=${{ runner.temp }}/llvm-16/bin/llvm-config" >> $GITHUB_ENV

      - name: Install latest Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup default stable
          for target in ${{ matrix.targets }}; do
            rustup target add $target
          done

      - name: Get version
        id: version
        run: echo ::set-output name=version::$(grep '^version =' server/Cargo.toml | sed 's/version = "\(.*\)"/\1/')

      - name: Build and Release
        run: |
          mkdir -p releases
          for target in ${{ matrix.targets }}; do
            if [[ "$target" == *"apple-darwin"* ]]; then
              export CC=$(pwd)/osxcross/target/bin/o64-clang
              export CXX=$(pwd)/osxcross/target/bin/o64-clang++
            fi
            cargo build --release --target $target --manifest-path=server/Cargo.toml || continue
            if [[ "$target" == *"windows"* ]]; then
              cp target/$target/release/server.exe releases/server-${{ steps.version.outputs.version }}-$target.exe
            else
              cp target/$target/release/server releases/server-${{ steps.version.outputs.version }}-$target
            fi
          done

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: server-v${{ steps.version.outputs.version }}
          name: Server Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: releases/
          asset_name: server-${{ steps.version.outputs.version }}-${{ matrix.os }}
          asset_content_type: application/octet-stream
        continue-on-error: true
