name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Release - ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      matrix:
        platform:
          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: server
            name: server-Darwin-x86_64.tar.gz
            command: build

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: server
            name: server-Darwin-aarch64.tar.gz
            command: build

          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: server
            name: server-Linux-x86_64.tar.gz
            command: build

          - release_for: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: server
            name: server-Linux-aarch64.tar.gz
            command: build

          - release_for: Windows-x86_64-msvc
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: server.exe
            name: server-Windows-x86_64-msvc.zip
            command: build

          - release_for: Windows-x86_64-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: server.exe
            name: server-Windows-x86_64-gnu.zip
            command: build

          - release_for: Windows-i686-msvc
            os: windows-latest
            target: i686-pc-windows-msvc
            bin: server.exe
            name: server-Windows-i686-msvc.zip
            command: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=$(grep '^version =' server/Cargo.toml | sed 's/version = \"\(.*\)\"/\1/')" >> $GITHUB_ENV

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release --manifest-path=server/Cargo.toml"
          strip: true



      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          cd -

      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.platform.name }}
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: server-v${{ env.version }}
          name: Server Release ${{ env.version }}
          draft: true
          prerelease: false
          files: "server-*"
          body_path: Changes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

