name: Publish to Snap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-to-snap:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - i386
          - amd64
          - armhf
          - arm64
          - ppc64el
          - s390x
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: diddlesnaps/snapcraft-multiarch-action@v1
        with:
          architecture: ${{ matrix.platform }}
          store-auth: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
