name: Publish to Snap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-to-snap:
    name: Release - ${{ matrix.platform }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - amd64
          - armhf
          - arm64
          - ppc64el
          - riscv64
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.platform }}

      - name: Set version
        id: version
        run: |
          VERSION=$(grep '^version =' server/Cargo.toml | sed 's/version = \"\(.*\)\"/\1/')
          
          FILE="snapcraft.yaml"
          
          echo "Updating at $FILE with version $VERSION"

          sed -i "s|{VERSION}|${VERSION}|g" "$FILE"

      - uses: diddlesnaps/snapcraft-multiarch-action@v1
        with:
          architecture: ${{ matrix.platform }}
          store-auth: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
