name: Publish to Snap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-to-snap:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snapcraft
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd lxd
          sudo snap install snapcraft --classic
          sudo lxd init --auto
          sudo usermod -aG lxd $USER
          newgrp lxd
          sudo lxd waitready
          sudo lxd init --auto
          snapcraft whoami
          snapcraft
          snapcraft upload --release=stable *.snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_BUILD_ENVIRONMENT: lxd
