# snapcraft && snapcraft upload --release stable *.snap

name: Publish to Snap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-to-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Snapcraft
        run: |
          sudo snap install snapcraft --classic
          echo "$SNAP_TOKEN" | snapcraft login --with -
          snapcraft
          snapcraft upload --release=stable *.snap
        env:
          SNAP_TOKEN: ${{secrets.SNAPCRAFT_STORE_CREDENTIALS}}
          SNAPCRAFT_BUILD_ENVIRONMENT: host