# snapcraft && snapcraft upload --release stable *.snap

name: Publish to Snap

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish-to-snap:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
#

      - name: Setup Snapcraft
        run: |
          sudo snap install snapcraft --classic
          echo "${SNAPCRAFT_STORE_CREDENTIALS}" > snap_login_file
          snapcraft login --with snap_login_file
          snapcraft
          snapcraft upload --release=stable *.snap
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
          SNAPCRAFT_BUILD_ENVIRONMENT: host
